/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Log.java
 *
 * Created on Sep 27, 2011, 11:49:31 AM
 */
package corallus.ui.window;

/**
 *
 * @author itakenami
 */
public class Log extends javax.swing.JFrame {

    private static Log instance;
    
    public static Log getInstance(){
        if(instance==null){
            instance = new Log();
        }
        return instance;
    }
    
    
    /** Creates new form Log */
    private Log() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("Log");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void addText(String txt){
        jTextArea1.append(txt);
        jTextArea1.append("\n");
    }
    
    public void limpar(){
        jTextArea1.setText("");
    }
}
